[versions]

compose = "1.3.2"
compose-bom = "2022.12.00"
compose-pager = "0.28.0"
compose-lifecycle = "2.6.0-alpha01"
hilt =  "2.44.2"

[libraries]
#android core
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"

#compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material = { module = "androidx.compose.material:material" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "compose-pager" }
compose-ui = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.6.1" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.5.3" }
compose-navigation-hilt = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-lifecycle" }
compose-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "compose-lifecycle" }
compose-lottie = { module = "com.airbnb.android:lottie-compose", version = "5.2.0" }

#Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-kapt = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

# firebase
firebase-bom = "com.google.firebase:firebase-bom:31.5.0"
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-await = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version = "1.6.4" }

# datastore
datastore = { module = "androidx.datastore:datastore-preferences", version = "1.0.0" }

# Timber
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

# coroutines
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.6.4" }

# Test
test-junit = { module = "junit:junit", version = "4.13.2" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
androidx-test-compose = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

# debug
debug-compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
debug-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

[bundles]
androidx-base = ["androidx-core", "androidx-lifecycle"]
androidx-compose = [
    "compose-ui",
    "compose-material",
    "compose-activity",
    "compose-navigation",
    "compose-navigation-hilt",
    "compose-viewmodel",
    "compose-lifecycle",
    "accompanist-pager",
    "compose-lottie",
]
firebase = [
    "firebase-firestore",
    "firebase-crashlytics",
    "firebase-analytics",
    "firebase-await",
]
test-base = ["test-junit"]
test-android = ["androidx-test-junit", "androidx-test-compose"]
debug-compose = ["debug-compose-tooling", "debug-compose-manifest"]
